apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: hs-developer-notes
build:
  artifacts:
  - image: honlsoft-notes
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s\*.yaml
portForward:
- resourceType: service
  resourceName: honlsoft-notes
  port: 80
  localPort: 9080
